trigger:
  - main

variables:
  - group: dev-ci-cd-demo-rg
  - name: notebookPath
    value: "notebooks"  

pool:
  vmImage: "windows-latest"

stages:
  - template: deploy.yml
    parameters:
      stageId: "Deploy_to_Dev_Env"
      env: "dev"
      environmentName: $(dev-env-name)
      resourceGroupName: $(dev-resource-grp-name)
      serviceConnection: $(dev-service-connection-name)
      notebookPath: $(notebookPath)
